language: elixir
cache:
  directories:
    - $HOME/.mix
elixir:
  - 1.7.2
otp_release:
  - 20.1
services:
  - elasticsearch
before_install:
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.4.deb 
  - sudo dpkg -i --force-confnew elasticsearch-6.2.4.deb 
  - sudo service elasticsearch restart
before_script:
  - sleep 10
script:
  - bin/setup