language: elixir
cache:
  directories:
    - $HOME/.mix
elixir:
  - 1.7.2
otp_release:
  - 20.1
env:
  - ELASTICSEARCH_VERSION=6.2.4
  - ELASTICSEARCH_VERSION=6.4.0
services:
  - elasticsearch
before_install:
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ELASTICSEARCH_VERSION}.deb && sudo dpkg -i --force-confnew elasticsearch-${ELASTICSEARCH_VERSION}.deb && sudo service elasticsearch restart
before_script:
  - sleep 10
script:
  - bin/setup